#!/bin/bash
# ard
# Allow non-admins to enable / disable Remote Management.
# chris.gerke@gmail.com

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //

chown root:admin "${path_root}/usr/local/bin/ard"
chmod 755 "${path_root}/usr/local/bin/ard"
chmod u+s "${path_root}/usr/local/bin/ard"

exit 0