#!/bin/bash
# ard
# Setup Remote Login and Remote Management.
# chris.gerke@gmail.com

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //

chown root:wheel "${path_root}/Library/LaunchDaemons/com.github.ard.plist"
chmod 644 "${path_root}/Library/LaunchDaemons/com.github.ard.plist"
chown root:wheel "${path_root}/Library/LaunchDaemons/com.github.ssh.plist"
chmod 644 "${path_root}/Library/LaunchDaemons/com.github.ssh.plist"

chown root:admin "${path_root}/usr/local/bin/ard"
chmod 755 "${path_root}/usr/local/bin/ard"
chmod u+s "${path_root}/usr/local/bin/ard"

exit 0